### ISSUE TITLE
Parsing the ! character

### ISSUE THREAD

**Issue by gl0ryus** [autobrr/omegabrr#12]
American Dad! has a exclamation point at the end. Omegabrr adds that to the list of shows but the release name doesnt include it.

`{"level":"debug","module":"release","indexer":"btn","filter":"!SONARR","release":"American.Dad.S19E21.Echoes.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb","time":"2022-12-14T14:54:48+01:00","message":"release rejected: match release not matching. got: American.Dad.S19E21.Echoes.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb want: *American?Dad!*`

**Comment by zze0s** [comment]
Fixed in #14
