### ISSUE TITLE
Allow environmental variables inside yaml

### ISSUE THREAD

**Issue by buroa** [autobrr/omegabrr#48]
It would be awesome to allow environmental variable substitution like this inside the configuration:

```
    - name: sonarr
      type: sonarr
      ...
      apikey: !env_var SONARR_API_KEY
      ...
 ```

This would make it easier to GitOps this application

https://recyclarr.dev/wiki/yaml/env-vars/

**Comment by zze0s** [comment]
Hey! Interesting idea.

What tools are you using for GitOps atm? Secrets will always be stored somewhere right. T

here's tools like Sealed Secrets and other alternatives that can be used as well without having to build support for it since they work with various config files.
