### ISSUE TITLE
Filling a filter with torrent titles currently in qbittorrent

### ISSUE THREAD

**Issue by marcodejongh** [autobrr/omegabrr#62]
Might be nice to be able to fill a filter with the strings of current torrents in qbittorrent, to help with setting up cross-seed.
Would only work when title based torrent matching is used, but that's probably fine for most users.
Happy to contribute back, just wanted to start a discussion about it first before pushing a PR

**Comment by KyleSanderson** [comment]
You can do this with https://github.com/kylesanderson/upgraderr

**Comment by marcodejongh** [comment]
With filterUpdate?

**Comment by KyleSanderson** [comment]
Yeah - docs are on .com. use a post script in your client with curl. I really wanted this feature in omegabrr and couldn't wait any longer.

**Comment by marcodejongh** [comment]
Awesome thx! I'll give it a go
