### ISSUE TITLE
Unable to run bin file direct

### ISSUE THREAD

**Issue by mgaulton** [autobrr/omegabrr#8]
No matter where I put the config, the omegabrr executable can't find the config.
Due to the way my host is setup with segmentation, I can't access the hosts from a docker container.
I'm hoping there is a way to work around this.
Opensuse Tumbleweed x64

Thanks.

**Comment by zze0s** [comment]
@mgaulton Hi, did you find a working solution?

To run it you need to pass the config path like `omegabrr arr --config /path/to/config.yaml`
