### ISSUE TITLE
Allow unmonitored

### ISSUE THREAD

**Issue by frant4** [autobrr/omegabrr#95]
I'd like to create filters for all items in arrs, but currently, there's no option to include unmonitored items. It would be great to have a configuration setting to allow this, this would also be beneficial for cross-seed filters.

**Comment by s0up4200** [comment]
Can you test pr-#96 and report back if that solves it for you? A docker image should be up in a few.

**Comment by frant4** [comment]
Yep, that solves it for me. Thanks!
